# Generated by Django 2.0.4 on 2018-10-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('users_number', models.PositiveIntegerField(verbose_name='users number')),
                ('start_date', models.DateField()),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_details', to='auth.Group', verbose_name='group (Added Automatically)')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['name'],
                'permissions': (('access_workshops', 'Allow User to see Workshops'),),
            },
        ),
    ]
