# Generated by Django 2.0.4 on 2019-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_auto_20190618_1805'),
        ('accounts', '0002_account_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='batches', to='library.Workshop'),
        ),
    ]
