let countries = [
    { value: 'ad', text: 'أندورا' },
    { value: 'ae', text: 'الإمارات العربية المتحدة' },
    { value: 'af', text: 'أفغانستان' },
    { value: 'ag', text: 'أنتيغوا وباربودا' },
    { value: 'ai', text: 'أنغويلا' },
    { value: 'al', text: 'ألبانيا' },
    { value: 'am', text: 'أرمينيا' },
    { value: 'ao', text: 'أنغولا' },
    { value: 'aq', text: 'القارة القطبية الجنوبية' },
    { value: 'ar', text: 'الأرجنتين' },
    { value: 'as', text: 'ساموا الأمريكية' },
    { value: 'at', text: 'النمسا' },
    { value: 'au', text: 'أستراليا' },
    { value: 'aw', text: 'أروبا' },
    { value: 'ax', text: 'أولند' },
    { value: 'az', text: 'أذربيجان' },
    { value: 'ba', text: 'البوسنة والهرسك' },
    { value: 'bb', text: 'باربادوس' },
    { value: 'bd', text: 'بنغلاديش' },
    { value: 'be', text: 'بلجيكا' },
    { value: 'bf', text: 'بوركينا فاسو' },
    { value: 'bg', text: 'بلغاريا' },
    { value: 'bh', text: 'البحرين' },
    { value: 'bi', text: 'بوروندي' },
    { value: 'bj', text: 'بنين' },
    { value: 'bl', text: 'سان بارتليمي' },
    { value: 'bm', text: 'برمودا' },
    { value: 'bn', text: 'بروناي' },
    { value: 'bo', text: 'بوليفيا' },
    { value: 'bq', text: 'الجزر الكاريبية الهولندية' },
    { value: 'br', text: 'البرازيل' },
    { value: 'bs', text: 'باهاماس' },
    { value: 'bt', text: 'بوتان' },
    { value: 'bv', text: 'جزيرة بوفيه' },
    { value: 'bw', text: 'بوتسوانا' },
    { value: 'by', text: 'بيلاروس' },
    { value: 'bz', text: 'بليز' },
    { value: 'ca', text: 'كندا' },
    { value: 'cc', text: 'جزر كوكس' },
    { value: 'cd', text: 'جمهورية الكونغو الديمقراطية' },
    { value: 'cf', text: 'جمهورية أفريقيا الوسطى' },
    { value: 'cg', text: 'جمهورية الكونغو' },
    { value: 'ch', text: 'سويسرا' },
    { value: 'ci', text: 'ساحل العاج' },
    { value: 'ck', text: 'جزر كوك' },
    { value: 'cl', text: 'تشيلي' },
    { value: 'cm', text: 'الكاميرون' },
    { value: 'cn', text: 'الصين' },
    { value: 'co', text: 'كولومبيا' },
    { value: 'cr', text: 'كوستاريكا' },
    { value: 'cu', text: 'كوبا' },
    { value: 'cv', text: 'الرأس الأخضر' },
    { value: 'cw', text: 'كوراساو' },
    { value: 'cx', text: 'جزيرة عيد الميلاد' },
    { value: 'cy', text: 'قبرص' },
    { value: 'cz', text: 'التشيك' },
    { value: 'de', text: 'ألمانيا' },
    { value: 'dj', text: 'جيبوتي' },
    { value: 'dk', text: 'الدنمارك' },
    { value: 'dm', text: 'دومينيكا' },
    { value: 'do', text: 'جمهورية الدومينيكان' },
    { value: 'dz', text: 'الجزائر' },
    { value: 'ec', text: 'الإكوادور' },
    { value: 'ee', text: 'إستونيا' },
    { value: 'eg', text: 'مصر' },
    { value: 'eh', text: 'الصحراء الغربية' },
    { value: 'er', text: 'إريتريا' },
    { value: 'es', text: 'إسبانيا' },
    { value: 'et', text: 'إثيوبيا' },
    { value: 'fi', text: 'فنلندا' },
    { value: 'fj', text: 'فيجي' },
    { value: 'fk', text: 'جزر فوكلاند' },
    { value: 'fm', text: 'ولايات ميكرونيسيا المتحدة' },
    { value: 'fo', text: 'جزر فارو' },
    { value: 'fr', text: 'فرنسا' },
    { value: 'ga', text: 'الغابون' },
    { value: 'gb', text: 'المملكة المتحدة' },
    { value: 'gd', text: 'غرينادا' },
    { value: 'ge', text: 'جورجيا' },
    { value: 'gf', text: 'غويانا الفرنسية' },
    { value: 'gg', text: 'غيرنزي' },
    { value: 'gh', text: 'غانا' },
    { value: 'gi', text: 'جبل طارق' },
    { value: 'gl', text: 'غرينلاند' },
    { value: 'gm', text: 'غامبيا' },
    { value: 'gn', text: 'غينيا' },
    { value: 'gp', text: 'غوادلوب' },
    { value: 'gq', text: 'غينيا الاستوائية' },
    { value: 'gr', text: 'اليونان' },
    { value: 'gs', text: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية' },
    { value: 'gt', text: 'غواتيمالا' },
    { value: 'gu', text: 'غوام' },
    { value: 'gw', text: 'غينيا بيساو' },
    { value: 'gy', text: 'غيانا' },
    { value: 'hk', text: 'هونغ كونغ' },
    { value: 'hm', text: 'جزيرة هيرد وجزر ماكدونالد' },
    { value: 'hn', text: 'هندوراس' },
    { value: 'hr', text: 'كرواتيا' },
    { value: 'ht', text: 'هايتي' },
    { value: 'hu', text: 'المجر' },
    { value: 'id', text: 'إندونيسيا' },
    { value: 'ie', text: 'جمهورية أيرلندا' },
    { value: 'il', text: 'إسرائيل' },
    { value: 'im', text: 'جزيرة مان' },
    { value: 'in', text: 'الهند' },
    { value: 'io', text: 'إقليم المحيط الهندي البريطاني' },
    { value: 'iq', text: 'العراق' },
    { value: 'ir', text: 'إيران' },
    { value: 'is', text: 'آيسلندا' },
    { value: 'it', text: 'إيطاليا' },
    { value: 'je', text: 'جيرزي' },
    { value: 'jm', text: 'جامايكا' },
    { value: 'jo', text: 'الأردن' },
    { value: 'jp', text: 'اليابان' },
    { value: 'ke', text: 'كينيا' },
    { value: 'kg', text: 'قيرغيزستان' },
    { value: 'kh', text: 'كمبوديا' },
    { value: 'ki', text: 'كيريباتي' },
    { value: 'km', text: 'جزر القمر' },
    { value: 'kn', text: 'سانت كيتس ونيفيس' },
    { value: 'kp', text: 'كوريا الشمالية' },
    { value: 'kr', text: 'كوريا الجنوبية' },
    { value: 'kw', text: 'الكويت' },
    { value: 'ky', text: 'جزر كايمان' },
    { value: 'kz', text: 'كازاخستان' },
    { value: 'la', text: 'لاوس' },
    { value: 'lb', text: 'لبنان' },
    { value: 'lc', text: 'سانت لوسيا' },
    { value: 'li', text: 'ليختنشتاين' },
    { value: 'lk', text: 'سريلانكا' },
    { value: 'lr', text: 'ليبيريا' },
    { value: 'ls', text: 'ليسوتو' },
    { value: 'lt', text: 'ليتوانيا' },
    { value: 'lu', text: 'لوكسمبورغ' },
    { value: 'lv', text: 'لاتفيا' },
    { value: 'ly', text: 'ليبيا' },
    { value: 'ma', text: 'المغرب' },
    { value: 'mc', text: 'موناكو' },
    { value: 'md', text: 'مولدوفا' },
    { value: 'me', text: 'الجبل الأسود' },
    { value: 'mf', text: 'سانت مارتن الفرنسية' },
    { value: 'mg', text: 'مدغشقر' },
    { value: 'mh', text: 'جزر مارشال' },
    { value: 'mk', text: 'جمهورية مقدونيا' },
    { value: 'ml', text: 'مالي' },
    { value: 'mm', text: 'بورما' },
    { value: 'mn', text: 'منغوليا' },
    { value: 'mo', text: 'ماكاو' },
    { value: 'mp', text: 'جزر ماريانا الشمالية' },
    { value: 'mq', text: 'مارتينيك' },
    { value: 'mr', text: 'موريتانيا' },
    { value: 'ms', text: 'مونتسرات' },
    { value: 'mt', text: 'مالطا' },
    { value: 'mu', text: 'موريشيوس' },
    { value: 'mv', text: 'جزر المالديف' },
    { value: 'mw', text: 'مالاوي' },
    { value: 'mx', text: 'المكسيك' },
    { value: 'my', text: 'ماليزيا' },
    { value: 'mz', text: 'موزمبيق' },
    { value: 'na', text: 'ناميبيا' },
    { value: 'nc', text: 'كاليدونيا الجديدة' },
    { value: 'ne', text: 'النيجر' },
    { value: 'nf', text: 'جزيرة نورفولك' },
    { value: 'ng', text: 'نيجيريا' },
    { value: 'ni', text: 'نيكاراغوا' },
    { value: 'nl', text: 'هولندا' },
    { value: 'no', text: 'النرويج' },
    { value: 'np', text: 'نيبال' },
    { value: 'nr', text: 'ناورو' },
    { value: 'nu', text: 'نييوي' },
    { value: 'nz', text: 'نيوزيلندا' },
    { value: 'om', text: 'سلطنة عمان' },
    { value: 'pa', text: 'بنما' },
    { value: 'pe', text: 'بيرو' },
    { value: 'pf', text: 'بولينزيا الفرنسية' },
    { value: 'pg', text: 'بابوا غينيا الجديدة' },
    { value: 'ph', text: 'الفلبين' },
    { value: 'pk', text: 'باكستان' },
    { value: 'pl', text: 'بولندا' },
    { value: 'pm', text: 'سان بيير وميكلون' },
    { value: 'pn', text: 'جزر بيتكيرن' },
    { value: 'pr', text: 'بورتوريكو' },
    { value: 'ps', text: 'دولة فلسطين' },
    { value: 'pt', text: 'البرتغال' },
    { value: 'pw', text: 'بالاو' },
    { value: 'py', text: 'باراغواي' },
    { value: 'qa', text: 'قطر' },
    { value: 're', text: 'لا ريونيون' },
    { value: 'ro', text: 'رومانيا' },
    { value: 'rs', text: 'صربيا' },
    { value: 'ru', text: 'روسيا' },
    { value: 'rw', text: 'رواندا' },
    { value: 'sa', text: 'السعودية' },
    { value: 'sb', text: 'جزر سليمان' },
    { value: 'sc', text: 'سيشل' },
    { value: 'sd', text: 'السودان' },
    { value: 'se', text: 'السويد' },
    { value: 'sg', text: 'سنغافورة' },
    { value: 'sh', text: 'سانت هيلينا وأسينشين وتريستان دا كونا' },
    { value: 'si', text: 'سلوفينيا' },
    { value: 'sj', text: 'سفالبارد ويان ماين' },
    { value: 'sk', text: 'سلوفاكيا' },
    { value: 'sl', text: 'سيراليون' },
    { value: 'sm', text: 'سان مارينو' },
    { value: 'sn', text: 'السنغال' },
    { value: 'so', text: 'الصومال' },
    { value: 'sr', text: 'سورينام' },
    { value: 'ss', text: 'جنوب السودان' },
    { value: 'st', text: 'ساو تومي وبرينسيب' },
    { value: 'sv', text: 'السلفادور' },
    { value: 'sx', text: 'سينت مارتن' },
    { value: 'sy', text: 'سوريا' },
    { value: 'sz', text: 'سوازيلاند' },
    { value: 'tc', text: 'جزر توركس وكايكوس' },
    { value: 'td', text: 'تشاد' },
    { value: 'tf', text: 'أراض فرنسية جنوبية وأنتارتيكية' },
    { value: 'tg', text: 'توغو' },
    { value: 'th', text: 'تايلاند' },
    { value: 'tj', text: 'طاجيكستان' },
    { value: 'tk', text: 'توكلو' },
    { value: 'tl', text: 'تيمور الشرقية' },
    { value: 'tm', text: 'تركمانستان' },
    { value: 'tn', text: 'تونس' },
    { value: 'to', text: 'تونغا' },
    { value: 'tr', text: 'تركيا' },
    { value: 'tt', text: 'ترينيداد وتوباغو' },
    { value: 'tv', text: 'توفالو' },
    { value: 'tw', text: 'تايوان' },
    { value: 'tz', text: 'تنزانيا' },
    { value: 'ua', text: 'أوكرانيا' },
    { value: 'ug', text: 'أوغندا' },
    { value: 'um', text: 'جزر الولايات المتحدة الصغيرة النائية' },
    { value: 'us', text: 'الولايات المتحدة' },
    { value: 'uy', text: 'الأوروغواي' },
    { value: 'uz', text: 'أوزبكستان' },
    { value: 'va', text: 'الفاتيكان' },
    { value: 'vc', text: 'سانت فنسنت والجرينادين' },
    { value: 've', text: 'فنزويلا' },
    { value: 'vg', text: 'الجزر العذراء البريطانية' },
    { value: 'vi', text: 'جزر العذراء الأمريكية' },
    { value: 'vn', text: 'فيتنام' },
    { value: 'vu', text: 'فانواتو' },
    { value: 'wf', text: 'والس وفوتونا' },
    { value: 'ws', text: 'ساموا' },
    { value: 'ye', text: 'اليمن' },
    { value: 'yt', text: 'مايوت' },
    { value: 'za', text: 'جنوب أفريقيا' },
    { value: 'zm', text: 'زامبيا' },
    { value: 'zw', text: 'زيمبابوي' }
]

module.exports = { countries }